In [11]:
pip install afinn

Requirement already satisfied: afinn in c:\users\admin\anaconda3\lib\site-packages (0.1)
Note: you may need to restart the kernel to use updated packages.

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from afinn import Afinn
import plotly.graph_objs as go

In [73]:
data = pd.read_csv(filepath_or_buffer='https://raw.githubusercontent.com/insaid2018/PGPDSAI/main/06%20Term%206%20-%20Machine%20Learning%20Advanced/02%20Module%202/data/ecommerce_reviews.csv')
print(f"Shape of the data:{data.shape}")
data.head()

Shape of the data:(23486, 10)

,Clothing ID,Age,Title,Review Text,Rating,Recommended?,Positive Feedback Count,Division Name,Department Name,Class Name
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [74]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              23486 non-null  int64
 1   Age                      23486 non-null  int64
 2   Title                    19676 non-null  object
 3   Review Text              22641 non-null  object
 4   Rating                   23486 non-null  int64
 5   Recommended?             23486 non-null  int64
 6   Positive Feedback Count  23486 non-null  int64
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB

In [75]:
data.describe()

,Clothing ID,Age,Rating,Recommended?,Positive Feedback Count
count,23486.000000,23486.000000,23486.000000,23486.000000,23486.000000
mean,918.118709,43.198544,4.196032,0.822362,2.535936
std,203.298980,12.279544,1.110031,0.382216,5.702202
min,0.000000,18.000000,1.000000,0.000000,0.000000
25%,861.000000,34.000000,4.000000,1.000000,0.000000
50%,936.000000,41.000000,5.000000,1.000000,1.000000
75%,1078.000000,52.000000,5.000000,1.000000,3.000000
max,1205.000000,99.000000,5.000000,1.000000,122.000000

In [76]:
data.skew()

C:\Users\admin\AppData\Local\Temp\ipykernel_1552\1188251951.py:1: FutureWarning:

Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

Clothing ID               -2.087636
Age                        0.525615
Rating                    -1.313529
Recommended?              -1.686952
Positive Feedback Count    6.472998
dtype: float64

In [77]:
data.dropna(subset = ['Title','Review Text'],inplace=True)

In [78]:
print(f"Shape of the data:{data.shape}")
data.head()

Shape of the data:(19675, 10)

,Clothing ID,Age,Title,Review Text,Rating,Recommended?,Positive Feedback Count,Division Name,Department Name,Class Name
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
5,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses
6,858,39,Cagrcoal shimmer fun,I aded this in my basket at hte last mintue to...,5,1,1,General Petite,Tops,Knits

In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19675 entries, 2 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              19675 non-null  int64
 1   Age                      19675 non-null  int64
 2   Title                    19675 non-null  object
 3   Review Text              19675 non-null  object
 4   Rating                   19675 non-null  int64
 5   Recommended?             19675 non-null  int64
 6   Positive Feedback Count  19675 non-null  int64
 7   Division Name            19662 non-null  object
 8   Department Name          19662 non-null  object
 9   Class Name               19662 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.7+ MB

In [80]:
affin = Afinn()
data['Review Text'] = data['Review Text'].str.lower()
data['Sentiment Score'] = data.apply(lambda row: affin.score(row['Review Text']),axis=1)

In [81]:
data.head()

,Clothing ID,Age,Title,Review Text,Rating,Recommended?,Positive Feedback Count,Division Name,Department Name,Class Name,Sentiment Score
2,1077,60,Some major design flaws,i had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses,5.0
3,1049,50,My favorite buy!,"i love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,22.0
4,847,47,Flattering shirt,this shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,6.0
5,1080,49,Not for the very petite,"i love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses,7.0
6,858,39,Cagrcoal shimmer fun,i aded this in my basket at hte last mintue to...,5,1,1,General Petite,Tops,Knits,-3.0

In [82]:
data.describe()

,Clothing ID,Age,Rating,Recommended?,Positive Feedback Count,Sentiment Score
count,19675.000000,19675.000000,19675.000000,19675.000000,19675.000000,19675.000000
mean,920.877865,43.257942,4.183685,0.818297,2.651080,8.458653
std,200.907460,12.256779,1.112055,0.385609,5.832711,5.613021
min,1.000000,18.000000,1.000000,0.000000,0.000000,-13.000000
25%,861.000000,34.000000,4.000000,1.000000,0.000000,5.000000
50%,936.000000,41.000000,5.000000,1.000000,1.000000,8.000000
75%,1078.000000,52.000000,5.000000,1.000000,3.000000,12.000000
max,1205.000000,99.000000,5.000000,1.000000,122.000000,39.000000

In [83]:
data.skew()

C:\Users\admin\AppData\Local\Temp\ipykernel_1552\1188251951.py:1: FutureWarning:

Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

Clothing ID               -2.101329
Age                        0.515732
Rating                    -1.281124
Recommended?              -1.651049
Positive Feedback Count    6.341121
Sentiment Score            0.506800
dtype: float64

## Exploratory Data Analysis

In [84]:
data.groupby(by='Rating').mean()

,Clothing ID,Age,Recommended?,Positive Feedback Count,Sentiment Score
Rating,,,,,
1,915.580318,43.399421,0.010130,3.366136,3.671491
2,926.324265,42.550735,0.058824,3.384559,5.079412
3,930.549513,42.157468,0.413961,3.183847,6.479708
4,923.379809,42.932851,0.965959,2.570996,8.047330
5,917.353969,43.715114,0.998068,2.424708,9.796523

In [85]:
data.corr()

,Clothing ID,Age,Rating,Recommended?,Positive Feedback Count,Sentiment Score
Clothing ID,1.000000,0.013409,-0.015009,-0.013884,0.041881,-0.014899
Age,0.013409,1.000000,0.034725,0.035287,0.041217,0.020000
Rating,-0.015009,0.034725,1.000000,0.793174,-0.056821,0.313794
Recommended?,-0.013884,0.035287,0.793174,1.000000,-0.059557,0.263807
Positive Feedback Count,0.041881,0.041217,-0.056821,-0.059557,1.000000,0.014143
Sentiment Score,-0.014899,0.020000,0.313794,0.263807,0.014143,1.000000

In [86]:
scaled_frame = data[['Age','Sentiment Score']]

In [87]:
inertia_vals = []
k_vals = [x for x in range(1,16)]
for i in k_vals:
  k_model = KMeans(n_clusters = i,max_iter=500,random_state=42)
  k_model.fit(scaled_frame)
  inertia_vals.append(k_model.inertia_)

In [94]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = k_vals, y = inertia_vals, mode = 'lines+markers'))
fig.show()

In [89]:
k_means = KMeans(n_clusters = 6,max_iter=500,random_state=42)
k_means.fit(scaled_frame)
scaled_frame['Labels'] = k_means.labels_ 
centers = k_means.cluster_centers_

C:\Users\admin\AppData\Local\Temp\ipykernel_1552\824072011.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [90]:
scaled_frame.head()

   Age  Sentiment Score  Labels
2   60              5.0       1
3   50             22.0       4
4   47              6.0       3
5   49              7.0       3
6   39             -3.0       5

In [91]:
scaled_frame.groupby(by="Labels").count()

         Age  Sentiment Score
Labels
0       2864             2864
1       2566             2566
2       3471             3471
3       3396             3396
4       2478             2478
5       4900             4900

In [92]:
scaled_frame.groupby(by="Labels")["Sentiment Score"].mean()

Labels
0    14.539804
1     9.379969
2     6.942956
3     4.874558
4    14.346247
5     5.002041
Name: Sentiment Score, dtype: float64

In [93]:
scaled_frame.groupby(by="Labels")["Age"].mean()

Labels
0    35.205307
1    65.059626
2    27.728608
3    51.775913
4    48.366425
5    39.061224
Name: Age, dtype: float64